name = "Frightful Exploration"
author = "idiot-shinuki"
version = "1.0.2+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cef9392d315c070bafd3b3d1c348c5b9075e91a8ca9787c0b80becfa7dbf5aa3"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
