name = "Frightful Exploration"
author = "idiot-shinuki"
version = "1.0.2+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2fff901940ea99de7a7b3e0ed79031c257a43eb9791a4e120f9424d09461202"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.x"]
