name = "Frightful Exploration"
author = "idiot-shinuki"
version = "1.0.2+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8025a42071ea1d2f40d394cc9644891004f8fefd64148efb13986a89756aef5"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
