name = "Frightful Exploration"
author = "idiot-shinuki"
version = "1.0.2+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c118acad71f40069d36cfdfd35d20fd2e933d2307f43d911f0529758f05dc0"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
