name = "Frightful Exploration"
author = "idiot-shinuki"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e5685ea95999a7ae45da10b464b92d01f530c7bee7748d4231cc45f7c326c0a"

[versions]
forge = "43.4.2"
minecraft = "1.19.2"
