#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Dec 15 20:38:10 EST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Insanity-Shader-Universal-v1.650.zip
enableShaders=true
